name: Validate Commit

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - edited

jobs:
  validate-commit:
    name: Validate Commit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Validate commit message
        uses: wagoid/commit-message-validator-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pattern: 
            "^(feat|fix|docs|style|refactor|perf|test|chore|revert|build)(\([\w\s-]*\))?: .+"
          error-message: "Commit message does not follow the conventional commits standard."